
export enum TipoAluguel{
    MORADIA_CONJUNTA = "MORADIA_CONJUNTA",
    LOCACAO = "LOCACAO",
    SUBLOCACAO = "SUBLOCACAO",

    APARTAMENTO = "APARTAMENTO",
    CASA = "CASA",
    REPUBLICA="REPUBLICA"
}